### ISSUE TITLE
SEQ Lab: Bug fixes

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#173]
For worksheet: EXP_21Feb2023

---

### SEQ Lab: Receive Library
- SEQ Lab: Receive Library, Add column to link GTAC@MGI 2D Barcode to sample as entity field or show existing 2D barcode linked from another lab ✔️

### SEQ Lab: KAPA Library Quantification
- SEQ Lab: KAPA Set Well Group, Ensure that 2D Barcode column is pulling correct barcode, meaning the GTAC@MGI barcode mentioned above ✔️

### SEQ Lab: KAPA Library Quantification
- SEQ Lab: KAPA Set Well Group, Add column Storage Location to indicate location in freezer system ⚠️

### SEQ Lab: KAPA Library Quantification
- SEQ Lab: KAPA Library Quantification Results, If possible, close Review Quantification Triplicates after hitting save button ⚠️

### SEQ Lab: Manual Illumina Library Dilutions
- SEQ Lab: Manual Illumina Dilutions Setup, Add column for GTAC@MGI 2D Barcode ✔️

### SEQ Lab: Manual Illumina Library Dilutions
- SEQ Lab: Manual Illumina Dilutions Setup, Add column Storage Location to indicate location in freezer system ⚠️

### SEQ Lab: Pooling Queue
- SEQ Lab: Pooling Queue, Molarity (nM), not being populated for all samples.  ✔️

### SEQ Lab: Manual Library Pooling
- SEQ Lab: Pool Grouping, Molarity (nM), not being populated for all samples. ✔️

### SEQ Lab: Manual Library Pooling
- SEQ Lab: Pool Grouping, 2D Barcode not being populated ✔️

### SEQ Lab: Manual Library Pooling
- SEQ Lab: Pool Grouping, Add column Storage Location to indicate location in freezer system ⚠️

### SEQ Lab: Manual Library Pooling
- SEQ Lab: Create Illumina Library Pools, Pool 2D Barcode should be a scanable entry ✔️

### SEQ Lab: Manual Library Pooling
- SEQ Lab: Create Illumina Library Pools, Library 2D Barcode should be a string of all Illumina entities going into the pool ✔️

### SEQ Lab: Manual Library Pooling
- SEQ Lab: Create Illumina Library Pools, Several columns on this sheet are not needed.  Service Request Number and all to the right of this column ✔️

### SEQ Lab: Manual Library Pooling
- SEQ Lab: Create Illumina Library Pools, Average Library Size (bp) column needed, but not being calculated using Calculate Average Library Size (bp) --> error ✔️

### SEQ Lab: NovaSeq Sequencing Queue
- SEQ Lab: Dilution Queue, Name of this protocol should be NovaSeq Sequencing Queue ✔️

### SEQ Lab: NovaSeq Sequencing Queue
- SEQ Lab: Dilution Queue, Molarity (nM) not being populated - this should be pulled from pool information or library if only 1 library ✔️

### SEQ Lab: NovaSeq Sequencing Queue
- SEQ Lab: Dilution Queue, Add columns Flow Cell Type, Flow Cell Cycles, Flow Cell Workflow, Sequencing Recipe ✔️

### SEQ Lab: NovaSeq Sequencing Queue
- SEQ Lab: Dilution Queue, After completing SEQ Lab: Manual Library Pooling two groupings were created for the same pool PL000057.  Only need one for the final pool. After completing the SEQ Lab: Manual Library Pooling and sending it to the next step (SEQ Lab: NovaSeq Sequencing Queue), there were two EXP_21Feb2023 in the Grouping: Experiment column on the left for PL00057, both of which had next step SEQ Lab: NovaSeq Sequencing Queue. I created the worksheet for SEQ Lab: NovaSeq Sequencing Queue in order to queue for sequencing, but the second still remains. Should be two here since the pool will only progress once into the queue. Make sense? Perhaps two were created because one set of samples did not need dilutions and went straight to the pooling queue and another set went through dilutions prior to pooling?

### SEQ Lab: NovaSeq Sequencing
- SEQ Lab: Illumina Setup, Service Request Number, Pool Plate, Pool Plate Position, Pool Concentration (ng/ul), Index Kit, i7 index Sequence, i5 index Sequence columns not needed ✔️

### SEQ Lab: NovaSeq Sequencing
- SEQ Lab: Illumina Setup, Add pool molarity (nM) ✔️

### SEQ Lab: NovaSeq Sequencing
- SEQ Lab: Illumina Setup, Samplesheet generator failing (Start column) ✔️

---

## Entity Updates

- Illumina Library - Client Assessed Molarity (nM) -Add, not required ✔️
- Illumina Library -Client Assessed Concentration (ng/ul) -	Add, not required ✔️

**Comment by mcordes-gtac** [comment]
SEQ Lab: Create Illumina Library Pools, Library 2D Barcode should be a string of all Illumina entities going into the pool
 
Can you clarify what you mean here? Right now, barcodes are generated based on a combination of the sample type and a unique ID.

**As you can see in the Parent GTAC IDs column, these is a comma separated listing of all of the GTAC ID contained within the pool.  Looking back at the previous worksheet, Pool Grouping, there is the 2D barcode column for each entity going into the pool (which is currently not populated, but should be).  I would like those barcodes listed (comma separated) in this field.**
 
SEQ Lab: Create Illumina Library Pools, Several columns on this sheet are not needed. Service Request Number and all to the right of this column
 
Since this is a Sample Protocol, ESP is pulling in all the entity fields for a new Illumina Library Pool entity, and unfortunately there is no way to hide or remove them.

**OK, no worries, was just trying to clean it up a bit.  Go ahead and hide what you can here**
 
SEQ Lab: Dilution Queue, Add columns Flow Cell Type, Flow Cell Cycles, Flow Cell Workflow, Sequencing Recipe
 
These fields should already be available upstream when the Dilution entity is created – do you want to just see these values for the dilution entity in a read-only format, or do you want the ability to change them at this step too?

**We do need to see those here, but I do not think we need the ability to change them.  I would assume if a change needs to be made, it can be made at the entity level and that would then populate correctly here?**

SEQ Lab: Dilution Queue, After completing SEQ Lab: Manual Library Pooling two groupings were created for the same pool PL000057.  Only need one for the final pool
 
I’m looking at the worksheets and the entity values, and I’m not quite seeing the issue. Can you clarify?

**After completing the SEQ Lab: Manual Library Pooling and sending it to the next step (SEQ Lab: NovaSeq Sequencing Queue), there were two EXP_21Feb2023 in the Grouping: Experiment column on the left for PL00057, both of which had next step SEQ Lab: NovaSeq Sequencing Queue.  I created the worksheet for SEQ Lab: NovaSeq Sequencing Queue in order to queue for sequencing, but the second still remains.  Should be two here since the pool will only progress once into the queue.  Make sense?  Perhaps two were created because one set of samples did not need dilutions and went straight to the pooling queue and another set went through dilutions prior to pooling?**

**Comment by tim-snyder-wustl** [comment]
@mcordes-gtac for:

### SEQ Lab: Manual Library Pooling
- SEQ Lab: Create Illumina Library Pools, Pool 2D Barcode should be a scanable entry

Do you just need to have an ESP-generated entity barcode shown for the new pool here?

**Comment by tim-snyder-wustl** [comment]
@mcordes-gtac I can't figure out why there was a duplicate PL00057 in the LIMS queue after the Manual Library Pooling workflow. It might be an ESP sample protocol bug, and not something related to the workflow implementation. Let me know if you encounter this issue again and I will put in a helpdesk ticket to L7.
