### ISSUE TITLE
Runsheet for Janus Dilutions

### ISSUE THREAD

**Issue by tim-snyder-wustl** [GTAC-MGI/GTAC-ESP-LIMS#81]

**Comment by mcordes-gtac** [comment]
[example-janus-dilution.csv](https://github.com/GTAC-MGI/GTAC-ESP-LIMS/files/8718536/example-janus-dilution.csv)

**Comment by tim-snyder-wustl** [comment]
Is this a duplicate of this: https://github.com/GTAC-MGI/GTAC-ESP-LIMS/issues/66 

There's a Janus Runsheet pipeline protocol in the Janus Dilution workflow - will this work or is a new dilution-specific runsheet needed? https://gtac-mgi-lims.wustl.edu/#/builders/workflows/details/f8469bba-0b1a-4e19-a0c1-a5b7e8d691de

Where is information pulled from? Is the template just empty or does it need data? Is the header always the same? Are there any calculations?

Need more detail. A full example of the protocol that has values to populate the CSV with real-world data would be helpful.

**Comment by mcordes-gtac** [comment]
@tim-snyder-wustl 
In all honesty, this workflow was put in as a placeholder and needs quite a bit of work on my part.  Is there a time we could meet to run through our current process to see if we can somehow use that as a template for this workflow.  The same can be said for the Janus pooling workflow.  I didn't do much work with these since it will require some communication between the lims and the instrument.
